apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-node
  labels:
    app: app-node
spec:
  replicas: 8
  selector:
    matchLabels:
      app: app-node
  template:
    metadata:
      labels:
        app: app-node
    spec:
      containers:
      - name: app-node-con
        image: us-east1-docker.pkg.dev/jovial-sunrise-471215-j6/my-docker-repo/teamcitytest:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: app-node-svc
  labels:
    app: app-node
spec:
  selector:
    app: app-node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000   
  type: LoadBalancer
